### ISSUE TITLE
Getting a warning after installation

### ISSUE THREAD

**Issue by igorkulman** [ljw1004/blog#2]
I installed the analyzer and I am getting this build warning

```
Analyzer assembly 'C:\Users\igor\.nuget\packages\PlatformSpecific.Analyzer\1.0.5\analyzers\dotnet\PlatformSpecific.Analyzer.dll' depends on 'Microsoft.CodeAnalysis.VisualBasic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but it was not found.
```

Is this normal? Or some kind of Nuget screw up?

**Comment by ljw1004** [comment]
I reported this to the Roslyn team. Bug filed here:

https://github.com/dotnet/roslyn/issues/7049

I see the fix was checked in on Dec 2015, so presumably the fix should be available in VS2015 Update 2. Please re-open bug if you keep seeing it!
