### ISSUE TITLE
Incorrectly marking a method as being version specific when an overload is version-specific

### ISSUE THREAD

**Issue by Sohra** [ljw1004/blog#3]
My example is [RfcommServiceProvider.StartAdvertising(StreamSocketListener)](https://msdn.microsoft.com/en-us/library/windows/apps/dn641723.aspx) listed on MSDN as being in the UniversalApiContract at version 1.  My code was calling this and being flagged as version specific.

An overload was added in version 2 [RfcommServiceProvider.StartAdvertising(StreamSocketListener, bool)](https://msdn.microsoft.com/en-us/library/windows/apps/mt622482.aspx) and I'm guessing this is what was causing my code to be flagged.

The analyzer should consider the parameters to distinguish which overload is being called and if, in fact, it is actually version-specific or not.

**Comment by ljw1004** [comment]
Closed in this repo, and re-opened in the analyzer's new repo
